apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: flask:1.0
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
