# Use an official MongoDB image as a parent image
FROM mongo

# Set the working directory to /data/db
WORKDIR /data/db

# Expose the default MongoDB port
EXPOSE 27017

# Start MongoDB when the container launches
CMD ["mongod"]
